name: Tests

on:
  pull_request:
    branches:
      - staging

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ga
          command: npm run cypress:run:ga
          wait-on: "http://localhost:3000"