name: Tests

on:
  pull_request:
    branches:
      - test

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    environment: dev
    env:
      CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL }}
      CYPRESS_TEST_ENV: ${{ vars.CYPRESS_TEST_ENV }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Use variables
        run: |
          echo "CYPRESS_BASE_URL : $CYPRESS_BASE_URL"
          echo "CYPRESS_TEST_ENV : $CYPRESS_TEST_ENV"
          echo "REACT_APP_HEAD_TEXT : $REACT_APP_HEAD_TEXT"

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ga
          command: npm run cypress:run:ga
          wait-on: "http://localhost:3000"